name: devVM
on:
  schedule:
    - cron: '42 13 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  init-vm:
    name: Run VM
    runs-on: ubuntu-22.04

    steps:
      - name: Dump context
        run: |
          echo '::group::Dump GitHub context'
          echo '${{ toJSON(github) }}'
          echo '::endgroup::'
          echo '::group::Dump job context'
          echo '${{ toJSON(job) }}'
          echo '::endgroup::'
          echo '::group::Dump steps context'
          echo '${{ toJSON(steps) }}'
          echo '::endgroup::'
          echo '::group::Dump runner context'
          echo '${{ toJSON(runner) }}'
          echo '::endgroup::'
          echo '::group::Dump strategy context'
          echo '${{ toJSON(strategy) }}'
          echo '::endgroup::'
          echo '::group::Dump matrix context'
          echo '${{ toJSON(matrix) }}'
          echo '::endgroup::'

      - name: Install
        run: |
          sudo apt-get update && \
          sudo apt-get install bison ca-certificates ccache cmake cmake-curses-gui dh-python doxygen expect flex flip gdal-bin git graphviz grass-dev libexiv2-dev libexpat1-dev libfcgi-dev libgdal-dev libgeos-dev libgsl-dev libpdal-dev libpq-dev libproj-dev libprotobuf-dev libqca-qt5-2-dev libqca-qt5-2-plugins libqscintilla2-qt5-dev libqt5opengl5-dev libqt5serialport5-dev libqt5sql5-sqlite libqt5svg5-dev libqt5webkit5-dev libqt5xmlpatterns5-dev libqwt-qt5-dev libspatialindex-dev libspatialite-dev libsqlite3-dev libsqlite3-mod-spatialite libyaml-tiny-perl libzip-dev libzstd-dev lighttpd locales ninja-build ocl-icd-opencl-dev opencl-headers pandoc pdal pkg-config poppler-utils protobuf-compiler pyqt5-dev pyqt5-dev-tools pyqt5.qsci-dev python3-all-dev python3-autopep8 python3-dateutil python3-dev python3-future python3-gdal python3-httplib2 python3-jinja2 python3-lxml python3-markupsafe python3-mock python3-nose2 python3-owslib python3-plotly python3-psycopg2 python3-pygments python3-pyproj python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtpositioning python3-pyqt5.qtsql python3-pyqt5.qtsvg python3-pyqt5.qtwebkit python3-pyqtbuild python3-requests python3-sip python3-six python3-termcolor python3-tz python3-yaml qt3d-assimpsceneimport-plugin qt3d-defaultgeometryloader-plugin qt3d-gltfsceneio-plugin qt3d-scene2d-plugin qt3d5-dev qtbase5-dev qtbase5-private-dev qtkeychain-qt5-dev qtpositioning5-dev qttools5-dev qttools5-dev-tools saga sip-tools spawn-fcgi xauth xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable xvfb

      - name: Install GUI
        run: |
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends ubuntu-desktop -y && \
          sudo apt-get install -y xrdp && \
          sudo apt-get install -y qtcreator
          sudo systemctl enable --now xrdp
#          sudo ufw allow from any to any port 3389 proto tcp
        if: github.event_name == 'workflow_dispatch'

      - name: Clone
        run: |
          pwd
          mkdir -p /home/runner/.cache/ccache
          mkdir -p ${HOME}/dev/cpp
          cd ${HOME}/dev/cpp
          git clone -b master --depth 1 --single-branch https://github.com/qgis/QGIS.git

      - uses: actions/cache@v3
        with:
          path: /home/runner/.cache/ccache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.sha }}
            ${{ runner.os }}-

      - name: Make
        run: |
          cd ${HOME}/dev/cpp/QGIS
          ccache -s -v
          ccache -z
          echo "::group::config"
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS:BOOL=OFF -DWITH_BINDINGS:BOOL=OFF -B ${HOME}/dev/cpp/buildQGIS
          echo "::endgroup::"
          echo "::group::make"
          cmake --build ${HOME}/dev/cpp/buildQGIS --target all -j2
          echo "::endgroup::"
          ccache -s -v
